version: '2.4'

services:
  db:
    image: mysql:8.0.21
    platform: linux/amd64
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    ports:
      - "33061:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: veric_backend_mvp
      MYSQL_USER: veric_backend_mvp
      MYSQL_PASSWORD: password
volumes:
  db_data:
